require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RegistrationsController do
  before :each do
    @worker = AccountWorker.create :name => "a", :password => "b"
  end

  # This should return the minimal set of attributes required to create a valid
  # Registration. As you add validations to Registration, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "aws_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RegistrationsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all registrations as @registrations" do
      registration = Registration.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:registrations)).to eq([registration])
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Registration" do
        expect {
          post :create, {:registration => valid_attributes}, valid_session
        }.to change(Registration, :count).by(1)
      end

      it "assigns a newly created registration as @registration" do
        post :create, {:registration => valid_attributes}, valid_session
        expect(assigns(:registration)).to be_a(Registration)
        expect(assigns(:registration)).to be_persisted
      end

      it "responds with the registration" do
        post :create, {:registration => valid_attributes}, valid_session
        json =  JSON.parse(response.body)
        json['name'].should == @worker.name
        json['password'].should == @worker.password
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved registration as @registration" do
        # Trigger the behavior that occurs when invalid params are submitted
        Registration.any_instance.stub(:save).and_return(false)
        post :create, {:registration => { "account_worker_id" => "invalid value" }}, valid_session
        expect(assigns(:registration)).to be_a_new(Registration)
      end
    end
  end

end
